name: healthcare-aiops
dependencies:
  - python>=3.8
  - pandas
  - numpy=1.18.5
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - tensorflow>=v2.4.1
  - pip
  - pip:
    - dc-cli
    - fasttext
    - pyvis
    - beautifulsoup4
