name: healthcare-aiops
dependencies:
  - python>=3.8
  - pandas
  - numpy=1.18.5
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
    - dc-cli
    - fasttext
    - pyvis
    - beautifulsoup4
    - mlflow
    - tensorflow==v2.2
